apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irmin-data
  labels:
    app: keyfender
    tier: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
