version: '3.1'

services:

  keyfender:
    image: keyfender/keyfender
    ports:
      - 4433:4433
      - 8080:8080
    command:
      - "/keyfender.socket"
      - "--password"
      - "secret"
      - "--logs"
      - "debug"
    restart: unless-stopped

  nginx-p11net:
    image: keyfender/nginx-p11net
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/certs:/certs:ro
      - ./config/nginx/key/import-key.json:/import-key.json:ro
      - ./config/nginx/html:/usr/share/nginx/html:ro
    ports:
      - 8443:443
    command:
      - "/bin/sh"
      - "-ex"
      - "-c"
      - |
        while ! nc -z keyfender 8080 2>/dev/null ; do echo "waiting for keyfender..."; sleep 1; done
        curl -s -X POST http://admin:secret@keyfender:8080/api/v0/keys -d @/import-key.json
        nginx -g "daemon off;"
    links:
      - keyfender
    restart: unless-stopped
